const SET_SERACH_ITEMS = 'SET_SERACH_ITEMS'
const CLEAR_SEARCHED_PRODCUTS = 'CLEAR_SEARCHED_PRODCUTS'
const SET_FILTER_DATA =  'SET_FILTER_DATA'
const REMOVE_FILTER_DATA =  'REMOVE_FILTER_DATA'


export {
  SET_SERACH_ITEMS,
  CLEAR_SEARCHED_PRODCUTS,
  SET_FILTER_DATA,
  REMOVE_FILTER_DATA
}
